### ISSUE TITLE
Order of term --> posting lists

### ISSUE THREAD

**Issue by noahpresler** [knowledge-discovery/hw1#6]
term1 IDF1 0:TF1 2:TF3 ...
term2 IDF2 1:TF2 4:TF5 ...

What order do we print these lines in?
Terms lexographically? By IDF? By overall frequency?

**Comment by vandurme** [comment]
The assignment gave no guidance.  If you want to print them lexicographically then great, but there's no requirement.  Sorting the Comm IDs matters obviously, since that establishes the integer to Comm mapping.  The order of the terms has no impact: presumably anyone who has completed the assignment could use anyone else's index file, whatever order the terms are in, and get the same result for queries.
